name: qiskit-terra-dev
channels:
    - conda-forge
dependencies:
    - python=3.8.*
    - pip
    - jupyter
    - nbconvert
    - numpy
    - matplotlib
    - pandas
    - seaborn
    - pip:
        - qiskit-aer-gpu
        - qiskit-ibmq-provider
        - pyarrow